# Generated by Django 2.2 on 2019-04-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover',
            field=models.BinaryField(blank=True),
        ),
    ]
