# Generated by Django 2.2 on 2019-04-25 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20190424_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(default='defaultBook.jpg', upload_to='book_pics'),
        ),
    ]
