# Generated by Django 2.2 on 2019-04-25 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='posts',
        ),
    ]
