# Generated by Django 2.2 on 2019-04-26 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20190426_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
        migrations.RemoveField(
            model_name='post',
            name='book',
        ),
    ]
