# Generated by Django 2.2.1 on 2019-05-07 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0013_auto_20190426_1051'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_posted',
            new_name='date_comment',
        ),
        migrations.AlterField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='shop.Tag'),
        ),
    ]
